name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./PhistiCardGame.sln  # Çözüm dosyasının yolunu burada belirtin
    - name: Build
      run: dotnet build ./PhistiCardGame.sln --no-restore  # Çözüm dosyasının yolunu burada belirtin
    - name: Test
      run: dotnet test ./PhistiCardGame.sln --no-build --verbosity normal  # Çözüm dosyasının yolunu burada belirtin
